GET http://localhost:8000/users

###

GET http://localhost:8000/users/47

###

POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "mario",
    "email": "dua@gmail.com",
    "password": "ada"
}
###
POST http://localhost:8000/users/login
Content-Type: application/json

{
    "email": "dua@gmail.com",
    "password": "kamu"
}

###
DELETE http://localhost:8000/users/45

###
POST http://localhost:8000/users/forgot-password
Content-Type: application/json

{
    "email": "tiga@gmail.com"
}

###
POST http://localhost:8000/users/reset-password/85391e07b57e45826f02e731028df960cd627d07
Content-Type: application/json

{
    "newPassword": "kamu"
}

### 
GET http://localhost:8000/protected-route
Content-Type: application/json
// nyoba di postman aja ini gk ribet